#!/usr/bin/env python3
"""
HULL INGEST — full-folder reader & equipment data extractor.
Usage:  python hull_ingest.py <hull_folder> [output.xlsx]

Walks EVERY file in the hull folder (no sampling). Extracts candidate
electrical equipment data (kW / V / Phase / Hz / Qty) from PDF text and
spreadsheets, recording the SOURCE DOCUMENT for every hit.

Output: Master_Source_List_<folder>.xlsx
  Columns: Source Doc | Rel Path | Line/Cell | Extracted Text | kW | V | Phase | Hz | Tag

RULES (per CLAUDE.md): extraction is an AID, not authority.
Marine_Electrical_Equipment_List.xlsx overrides everything.
Rows the parser is unsure about are tagged [REVIEW]; scanned/image PDFs
with no text layer are tagged [MISSING-TEXT] (need OCR or manual read).
Requires: openpyxl, pdfminer.six  (pip install openpyxl pdfminer.six)
"""
import os, re, sys
import openpyxl
from openpyxl.styles import Font, PatternFill

try:
    from pdfminer.high_level import extract_text
    HAVE_PDF = True
except ImportError:
    HAVE_PDF = False

KW   = re.compile(r"(\d+(?:[.,]\d+)?)\s*(?:e?kW|KW)\b")
VOLT = re.compile(r"(\d{2,4})\s*(?:V|VAC|VDC|volt)", re.I)
PHASE= re.compile(r"(3|1)\s*(?:PH|phase|Ø)|(?:\bDC\b)", re.I)
HZ   = re.compile(r"(50|60)\s*Hz", re.I)
QTY  = re.compile(r"(?:qty|quantity)\s*[:=]?\s*(\d+)", re.I)
SKIP_EXT = {".jpg",".jpeg",".png",".gif",".bmp",".tif",".tiff",".dwg",".zip",".rar",".7z",".exe",".tmp"}

def hits_from_text(text, maxlines=4000):
    out = []
    for i, line in enumerate(text.splitlines()[:maxlines], 1):
        if KW.search(line) or (VOLT.search(line) and PHASE.search(line)):
            kw = KW.search(line); v = VOLT.search(line)
            ph = PHASE.search(line); hz = HZ.search(line)
            out.append((i, line.strip()[:180],
                        kw.group(1).replace(",",".") if kw else "",
                        v.group(1) if v else "",
                        (ph.group(0).upper().replace(" ","") if ph else ""),
                        hz.group(1) if hz else ""))
    return out

def scan_pdf(path):
    if not HAVE_PDF:
        return None, "[MISSING-TEXT] pdfminer not installed"
    try:
        text = extract_text(path) or ""
    except Exception as e:
        return None, f"[ERROR] {e}"
    if len(text.strip()) < 40:
        return None, "[MISSING-TEXT] no text layer (scanned?) — OCR or manual read required"
    return hits_from_text(text), None

def scan_xlsx(path):
    out = []
    try:
        wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    except Exception as e:
        return None, f"[ERROR] {e}"
    for ws in wb.worksheets:
        for r, row in enumerate(ws.iter_rows(values_only=True), 1):
            line = " | ".join(str(c) for c in row if c is not None)
            if not line:
                continue
            for hit in hits_from_text(line):
                out.append((f"{ws.title}!R{r}", hit[1], hit[2], hit[3], hit[4], hit[5]))
            if r > 3000:
                break
    wb.close()
    return out, None

def main(folder, out_path=None):
    folder = os.path.abspath(folder)
    name = os.path.basename(folder.rstrip("/\\"))
    out_path = out_path or f"Master_Source_List_{name}.xlsx"
    wb = openpyxl.Workbook(); ws = wb.active; ws.title = "MASTER SOURCE LIST"
    ws.append([f"MASTER SOURCE LIST — {name} — generated by hull_ingest.py"])
    ws.append(["NOTE: extraction aid only. Marine_Electrical_Equipment_List.xlsx is authoritative. Verify every row."])
    ws.append([])
    hdr = ["Source Doc","Rel Path","Line/Cell","Extracted Text","kW","V","Phase","Hz","Tag"]
    ws.append(hdr)
    for c in ws[4]: c.font = Font(bold=True)
    files = problems = rows = 0
    for dirpath, dirs, fns in os.walk(folder):
        dirs[:] = [d for d in dirs if not d.startswith((".", "_Archive"))]
        for fn in sorted(fns):
            ext = os.path.splitext(fn)[1].lower()
            if ext in SKIP_EXT: continue
            p = os.path.join(dirpath, fn); rel = os.path.relpath(p, folder)
            files += 1
            hits = err = None
            if ext == ".pdf":           hits, err = scan_pdf(p)
            elif ext in (".xlsx",".xlsm"): hits, err = scan_xlsx(p)
            elif ext in (".txt",".csv",".md"):
                try: hits = hits_from_text(open(p, errors="ignore").read())
                except Exception as e: err = f"[ERROR] {e}"
            else:
                continue
            if err:
                ws.append([fn, rel, "", "", "", "", "", "", err]); problems += 1; continue
            for h in (hits or []):
                if ext == ".pdf":
                    ws.append([fn, rel, f"L{h[0]}", h[1], h[2], h[3], h[4], h[5], "[REVIEW]"])
                else:
                    ws.append([fn, rel, h[0], h[1], h[2], h[3], h[4], h[5], "[REVIEW]"])
                rows += 1
    ws.append([]); ws.append([f"FILES SCANNED: {files}", f"DATA ROWS: {rows}", f"PROBLEM FILES: {problems}"])
    for col, w in zip("ABCDEFGHI", (38, 50, 9, 70, 7, 7, 7, 6, 30)):
        ws.column_dimensions[col].width = w
    wb.save(out_path)
    print(f"✓ {out_path}: {files} files scanned, {rows} extracted rows, {problems} problem files")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(1)
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
